#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Get To Work · WebGL 一键构建脚本
--------------------------------
把 AssetRipper 导出的工程，用 Unity 6000.0.35f1 重新编译成浏览器可跑版本，
产物 + build.json 落到 game/build/（分片打包交给 split_package.py）。

用法：
  python tools/build_webgl.py \
      --project "D:/GetToWorkUnity/ExportedProject" \
      --out "../../game/build" \
      [--unity "D:/Unity/6000.0.35f1/Editor/Unity.exe"] \
      [--skip-prepare]

流程：
  1. fix_circular_refs.py    —— 断开「资源 -> 场景对象」反向引用（否则导入死循环 + 段错误）
  2. prepare_unity_project.py —— 生成 manifest.json / 隔离包 DLL 与 Windows 专属原生插件
  3. 移出 Assets/StreamingAssets/aa（4GB 的 StandaloneWindows64 bundle，不能进 WebGL 产物）
  4. 注入 Assets/Editor/GTWWebGL.cs + Assets/csc.rsp → Unity 批处理打包
  5. 收集产物 → build.json

已知必需的两个补丁（都已在脚本里自动处理，改动别丢）：
  * 编译宏 ENABLE_UNITY_COLLECTIONS_CHECKS
      com.unity.collections 2.5.1 的 NativeList.AsReadOnly 在未定义该宏时调用 2 参数
      NativeArray<T>.ReadOnly 构造，而引擎只暴露 3 参数版本 -> CS7036。
  * Assets/csc.rsp 显式 -r UnityEngine.dll
      DOTween.dll 引用旧 UnityEngine facade，WebGL 播放器编译期不给该引用
      -> MovingObject.cs CS0012（Vector3/Quaternion 找不到程序集）。
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time

DEFAULT_UNITY = r"D:\Unity\6000.0.35f1\Editor\Unity.exe"

# ---- 注入到工程里的 Editor 构建脚本 -------------------------------------------
# 已废弃：现在统一用 tools/unity_editor/GTWWebGL.cs（支持切平台 / 宏 / Addressables），
# 由 run_unity() 直接拷贝进 Assets/Editor/。下面这段保留仅作历史参考。
_EDITOR_CS_DEPRECATED = r'''// Auto-generated by build_webgl.py — WebGL 批处理构建
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

public class BuildWebGL
{
    const string OutDir = "Builds/WebGL";

    public static void PerformBuild()
    {
        try
        {
            // 1) 切到 WebGL 平台
            if (EditorUserBuildSettings.activeBuildTarget != BuildTarget.WebGL)
            {
                Debug.Log("[BuildWebGL] switching to WebGL ...");
                EditorUserBuildSettings.SwitchActiveBuildTarget(BuildTargetGroup.WebGL, BuildTarget.WebGL);
            }

            // 2) Player 设置
            PlayerSettings.companyName = "DaXuanBa";
            PlayerSettings.productName = "Get To Work";
            PlayerSettings.defaultWebScreenWidth = 1280;
            PlayerSettings.defaultWebScreenHeight = 720;
            PlayerSettings.runInBackground = true;

#if UNITY_WEBGL
#endif
            // GitHub Pages 无法下发 COOP/COEP → 必须关线程
            PlayerSettings.WebGL.threadsSupport = false;
            // Brotli + JS 解压兜底：静态托管没有 Content-Encoding 头，必须开兜底
            PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Brotli;
            PlayerSettings.WebGL.decompressionFallback = true;
            PlayerSettings.WebGL.dataCaching = true;
            PlayerSettings.WebGL.emscriptenArgs = "";
            PlayerSettings.WebGL.template = "APPLICATION:Default";

            // 反编译工程大量使用反射（Zenject / Odin / BehaviorDesigner），剥离必须关
            PlayerSettings.SetScriptingBackend(NamedBuildTarget.WebGL, ScriptingImplementation.IL2CPP);
            PlayerSettings.SetManagedStrippingLevel(NamedBuildTarget.WebGL, ManagedStrippingLevel.Disabled);
            PlayerSettings.SetIl2CppCompilerConfiguration(NamedBuildTarget.WebGL, Il2CppCompilerConfiguration.Release);
            PlayerSettings.SetIl2CppCodeGeneration(NamedBuildTarget.WebGL, Il2CppCodeGeneration.OptimizeSize);

            AssetDatabase.SaveAssets();

            // 3) 场景列表
            var scenes = new List<string>();
            foreach (var s in EditorBuildSettings.scenes)
                if (s.enabled && !string.IsNullOrEmpty(s.path)) scenes.Add(s.path);

            if (scenes.Count == 0)
            {
                foreach (var guid in AssetDatabase.FindAssets("t:Scene"))
                    scenes.Add(AssetDatabase.GUIDToAssetPath(guid));
                scenes = scenes.OrderBy(p => p).ToList();
                Debug.Log("[BuildWebGL] EditorBuildSettings 为空，回退到全部场景: " + scenes.Count);
            }
            Debug.Log("[BuildWebGL] scenes (" + scenes.Count + "): " + string.Join(", ", scenes));

            if (Directory.Exists(OutDir)) Directory.Delete(OutDir, true);
            Directory.CreateDirectory(OutDir);

            var opts = new BuildPlayerOptions
            {
                scenes = scenes.ToArray(),
                locationPathName = OutDir,
                target = BuildTarget.WebGL,
                options = BuildOptions.None,
            };

            var report = BuildPipeline.BuildPlayer(opts);
            var sum = report.summary;
            Debug.Log(string.Format("[BuildWebGL] result={0} size={1}MB errors={2} warnings={3}",
                sum.result, (sum.totalSize / 1048576.0).ToString("F1"), sum.totalErrors, sum.totalWarnings));

            if (sum.result != BuildResult.Success)
            {
                foreach (var step in report.steps)
                    foreach (var msg in step.messages)
                        if (msg.type == LogType.Error || msg.type == LogType.Exception)
                            Debug.LogError("[BuildWebGL] " + msg.content);
                EditorApplication.Exit(1);
                return;
            }
            EditorApplication.Exit(0);
        }
        catch (System.Exception e)
        {
            Debug.LogError("[BuildWebGL] EXCEPTION: " + e);
            EditorApplication.Exit(1);
        }
    }
}
'''

CONTEXT_ATTRS = {
    "powerPreference": "high-performance",
    "preserveDrawingBuffer": False,
    "failIfMajorPerformanceCaveat": False,
    "antialias": True,
    "alpha": False,
}


def run_prepare(project: str, unity_dir: str | None = None) -> None:
    """步骤 1：工程后处理（断循环引用 + 生成 manifest + 隔离插件）。"""
    here = os.path.dirname(os.path.abspath(__file__))

    # 1a) 断开「资源 -> 场景对象」反向引用
    #     否则 Unity 导入时刷 Do not use ReadObjectThreaded on scene objects! 并最终段错误
    fix = os.path.join(here, "fix_circular_refs.py")
    if os.path.isfile(fix):
        print("[1a] 断开循环引用 ------------------------------")
        env = dict(os.environ, GTW_PROJECT=project)
        subprocess.run([sys.executable, fix, "--apply"], check=False, env=env)
    else:
        print("[!] 未找到 fix_circular_refs.py，跳过")

    # 1b) manifest + 插件隔离
    prep = os.path.join(here, "prepare_unity_project.py")
    if not os.path.isfile(prep):
        print("[!] 未找到 prepare_unity_project.py，跳过")
        return
    print("[1b] 工程后处理 ------------------------------")
    cmd = [sys.executable, prep, "--project", project]
    if unity_dir:
        cmd += ["--unity-dir", unity_dir]
    subprocess.run(cmd, check=False)


def exclude_windows_addressables(project: str) -> None:
    """
    把 Assets/StreamingAssets/aa 移出工程。

    那是 AssetRipper 从游戏包里挖出来的 **StandaloneWindows64** Addressables bundle（约 4GB），
    原样留着会被塞进 WebGL 产物；WebGL 的 bundle 需要重新构建（见 GTWWebGL.PerformFullBuild）。
    """
    src = os.path.join(project, "Assets", "StreamingAssets", "aa")
    if not os.path.isdir(src):
        return
    dst = os.path.join(os.path.dirname(project.rstrip("\\/")), "aa_win_backup", "aa")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if os.path.exists(dst):
        print("[*] 备份已存在，跳过移动:", dst)
        return
    print("[*] 移出 Windows 版 Addressables:", src, "->", dst)
    shutil.move(src, dst)


# 历史遗留：曾用 csc.rsp 追加 `-r UnityEngine.dll` 修 DOTween CS0012，
# 但会让 UnityLinker 找不到 UnityEngine.SharedInternalsModule 而崩，已废弃（见 run_unity）。
CSC_RSP_TEMPLATE = None  # deprecated


def run_unity(unity_exe: str, project: str, log_path: str, unity_dir: str, method: str) -> int:
    """步骤 2：注入构建脚本 + 命令行构建。"""
    here = os.path.dirname(os.path.abspath(__file__))
    editor_dir = os.path.join(project, "Assets", "Editor")
    os.makedirs(editor_dir, exist_ok=True)

    # 2a) 注入构建脚本（仓库 tools/unity_editor/GTWWebGL.cs 为准）
    src_editor = os.path.join(here, "unity_editor", "GTWWebGL.cs")
    if not os.path.isfile(src_editor):
        raise RuntimeError("缺少 tools/unity_editor/GTWWebGL.cs")
    shutil.copy2(src_editor, os.path.join(editor_dir, "GTWWebGL.cs"))

    # 注意：历史上曾用 Assets/csc.rsp 追加 `-r UnityEngine.dll` 试图修 DOTween 的 CS0012，
    # 但实测会让 UnityLinker 找不到 UnityEngine.SharedInternalsModule 而崩。
    # MovingObject.cs 已改为纯协程（不再依赖 DOTween），所以这里**不再写 csc.rsp**。
    # 若项目里残留了 csc.rsp，删掉它，否则 WebGL 链接阶段必崩。
    rsp = os.path.join(project, "Assets", "csc.rsp")
    if os.path.isfile(rsp):
        os.remove(rsp)
        print("[*] 删除残留 csc.rsp:", rsp)

    # Unity 的 WebGL 构建会调用 node（uglify / emscripten）。若环境里残留
    # NODE_OPTIONS / ELECTRON_RUN_AS_NODE（例如被其它 IDE 注入），会劫持 node 导致崩溃，
    # 这里显式清掉这两个变量。
    safe_env = dict(os.environ)
    safe_env.pop("NODE_OPTIONS", None)
    safe_env.pop("ELECTRON_RUN_AS_NODE", None)

    cmd = [
        unity_exe, "-batchmode", "-quit", "-nographics", "-accept-apiupdate",
        "-projectPath", project,
        "-executeMethod", method,
        "-buildTarget", "WebGL",
        "-logFile", log_path,
    ]
    print("[2] Unity 构建 ------------------------------")
    print("     ", " ".join(cmd))
    t0 = time.time()
    proc = subprocess.run(cmd, env=safe_env)
    print("[*] Unity 退出码: %s  耗时 %.1f 分钟" % (proc.returncode, (time.time() - t0) / 60))
    return proc.returncode


def collect_build(src_build_dir: str, out_dir: str, company: str, product: str) -> dict:
    """步骤 3：收集产物并生成 build.json。"""
    print("[3/3] 收集产物 ------------------------------")
    os.makedirs(out_dir, exist_ok=True)
    for name in os.listdir(src_build_dir):
        s = os.path.join(src_build_dir, name)
        d = os.path.join(out_dir, name)
        if os.path.isdir(s):
            if os.path.exists(d):
                shutil.rmtree(d)
            shutil.copytree(s, d)
        else:
            shutil.copy2(s, d)

    build_sub = os.path.join(out_dir, "Build")
    if not os.path.isdir(build_sub):
        build_sub = out_dir

    def find(ext):
        # 优先 Unity 压缩变体（WebGL.data.unityweb 等），loader.js 内置解压
        for f in sorted(os.listdir(build_sub)):
            if f.lower().endswith(ext.lower() + ".unityweb"):
                return f
        for f in sorted(os.listdir(build_sub)):
            if f.lower().endswith(ext.lower()):
                return f
        return None

    loader, data, framework, code = (
        find(".loader.js"), find(".data"), find(".framework.js"), find(".wasm"),
    )
    missing = [n for n, v in
               (("loader.js", loader), (".data", data),
                (".framework.js", framework), (".wasm", code)) if not v]
    if missing:
        raise RuntimeError("构建产物不完整，缺少: %s（见 Unity 日志）" % ", ".join(missing))

    cfg = {
        "loaderUrl": "build/" + loader,
        "dataUrl": "build/" + data,
        "frameworkUrl": "build/" + framework,
        "codeUrl": "build/" + code,
        "streamingAssetsUrl": "build/StreamingAssets",
        "companyName": company,
        "productName": product,
        "webglContextAttributes": CONTEXT_ATTRS,
    }
    with open(os.path.join(out_dir, "build.json"), "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    print(json.dumps(cfg, ensure_ascii=False, indent=2))
    return cfg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--unity", default=DEFAULT_UNITY, help="Unity Editor 路径")
    ap.add_argument("--project", required=True, help="AssetRipper 导出的工程根")
    ap.add_argument("--out", default="game/build", help="WebGL 产物输出目录")
    ap.add_argument("--company", default="DaXuanBa")
    ap.add_argument("--product", default="Get To Work")
    ap.add_argument("--skip-prepare", action="store_true")
    ap.add_argument("--skip-unity", action="store_true", help="只做收集（复用已有 Builds/WebGL）")
    ap.add_argument("--full", action="store_true",
                    help="同时重建 Addressables（关卡场景走 LoadSceneAsync，必须为此平台重打包）")
    args = ap.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = args.out if os.path.isabs(args.out) else os.path.join(repo_root, args.out)
    log_path = os.path.join(args.project, "..", "logs", "webgl_build.log")
    log_path = os.path.abspath(log_path)
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    src_build = os.path.join(args.project, "Builds", "WebGL")

    # Unity 安装根目录（从 Unity.exe 反推：<dir>/Editor/Unity.exe）
    unity_dir = os.path.dirname(os.path.dirname(os.path.abspath(args.unity)))

    if not args.skip_prepare:
        run_prepare(args.project, unity_dir)

    exclude_windows_addressables(args.project)

    if not args.skip_unity:
        if not os.path.isfile(args.unity):
            print("[!] 找不到 Unity: %s" % args.unity)
            sys.exit(1)
        method = "GTWWebGL.PerformFullBuild" if args.full else "GTWWebGL.PerformBuild"
        if run_unity(args.unity, args.project, log_path, unity_dir, method) != 0:
            print("[!] Unity 构建失败，详见日志: %s" % log_path)
            sys.exit(1)

    if not os.path.isdir(src_build):
        print("[!] 未找到构建输出: %s" % src_build)
        sys.exit(1)

    collect_build(src_build, out_dir, args.company, args.product)
    print("[*] 完成 →", out_dir)
    print("[*] 下一步: python tools/split_package.py --build %s --site .." % out_dir)


if __name__ == "__main__":
    main()
