#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Get To Work · WebGL 一键构建脚本
--------------------------------
把 AssetRipper 导出的工程，用 Unity 6000.0.35f1 重新编译成浏览器可跑版本，
产物 + build.json 落到 game/build/（分片打包交给 split_package.py）。

用法：
  python tools/build_webgl.py \
      --project "D:/GetToWorkUnity/ExportedProject" \
      --out "../../game/build" \
      [--unity "D:/Unity/6000.0.35f1/Editor/Unity.exe"] \
      [--skip-prepare]

流程：
  1. prepare_unity_project.py —— 生成 manifest.json / 隔离重复 DLL 与 Windows 专属插件
  2. 注入 Assets/Editor/BuildWebGL.cs 并命令行跑 Unity 打包
  3. 收集产物 → build.json
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time

DEFAULT_UNITY = r"D:\Unity\6000.0.35f1\Editor\Unity.exe"

# ---- 注入到工程里的 Editor 构建脚本 -------------------------------------------
EDITOR_CS = r'''// Auto-generated by build_webgl.py — WebGL 批处理构建
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

public class BuildWebGL
{
    const string OutDir = "Builds/WebGL";

    public static void PerformBuild()
    {
        try
        {
            // 1) 切到 WebGL 平台
            if (EditorUserBuildSettings.activeBuildTarget != BuildTarget.WebGL)
            {
                Debug.Log("[BuildWebGL] switching to WebGL ...");
                EditorUserBuildSettings.SwitchActiveBuildTarget(BuildTargetGroup.WebGL, BuildTarget.WebGL);
            }

            // 2) Player 设置
            PlayerSettings.companyName = "DaXuanBa";
            PlayerSettings.productName = "Get To Work";
            PlayerSettings.defaultWebScreenWidth = 1280;
            PlayerSettings.defaultWebScreenHeight = 720;
            PlayerSettings.runInBackground = true;

#if UNITY_WEBGL
#endif
            // GitHub Pages 无法下发 COOP/COEP → 必须关线程
            PlayerSettings.WebGL.threadsSupport = false;
            // Brotli + JS 解压兜底：静态托管没有 Content-Encoding 头，必须开兜底
            PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Brotli;
            PlayerSettings.WebGL.decompressionFallback = true;
            PlayerSettings.WebGL.dataCaching = true;
            PlayerSettings.WebGL.emscriptenArgs = "";
            PlayerSettings.WebGL.template = "APPLICATION:Default";

            // 反编译工程大量使用反射（Zenject / Odin / BehaviorDesigner），剥离必须关
            PlayerSettings.SetScriptingBackend(NamedBuildTarget.WebGL, ScriptingImplementation.IL2CPP);
            PlayerSettings.SetManagedStrippingLevel(NamedBuildTarget.WebGL, ManagedStrippingLevel.Disabled);
            PlayerSettings.SetIl2CppCompilerConfiguration(NamedBuildTarget.WebGL, Il2CppCompilerConfiguration.Release);
            PlayerSettings.SetIl2CppCodeGeneration(NamedBuildTarget.WebGL, Il2CppCodeGeneration.OptimizeSize);

            AssetDatabase.SaveAssets();

            // 3) 场景列表
            var scenes = new List<string>();
            foreach (var s in EditorBuildSettings.scenes)
                if (s.enabled && !string.IsNullOrEmpty(s.path)) scenes.Add(s.path);

            if (scenes.Count == 0)
            {
                foreach (var guid in AssetDatabase.FindAssets("t:Scene"))
                    scenes.Add(AssetDatabase.GUIDToAssetPath(guid));
                scenes = scenes.OrderBy(p => p).ToList();
                Debug.Log("[BuildWebGL] EditorBuildSettings 为空，回退到全部场景: " + scenes.Count);
            }
            Debug.Log("[BuildWebGL] scenes (" + scenes.Count + "): " + string.Join(", ", scenes));

            if (Directory.Exists(OutDir)) Directory.Delete(OutDir, true);
            Directory.CreateDirectory(OutDir);

            var opts = new BuildPlayerOptions
            {
                scenes = scenes.ToArray(),
                locationPathName = OutDir,
                target = BuildTarget.WebGL,
                options = BuildOptions.None,
            };

            var report = BuildPipeline.BuildPlayer(opts);
            var sum = report.summary;
            Debug.Log(string.Format("[BuildWebGL] result={0} size={1}MB errors={2} warnings={3}",
                sum.result, (sum.totalSize / 1048576.0).ToString("F1"), sum.totalErrors, sum.totalWarnings));

            if (sum.result != BuildResult.Success)
            {
                foreach (var step in report.steps)
                    foreach (var msg in step.messages)
                        if (msg.type == LogType.Error || msg.type == LogType.Exception)
                            Debug.LogError("[BuildWebGL] " + msg.content);
                EditorApplication.Exit(1);
                return;
            }
            EditorApplication.Exit(0);
        }
        catch (System.Exception e)
        {
            Debug.LogError("[BuildWebGL] EXCEPTION: " + e);
            EditorApplication.Exit(1);
        }
    }
}
'''

CONTEXT_ATTRS = {
    "powerPreference": "high-performance",
    "preserveDrawingBuffer": False,
    "failIfMajorPerformanceCaveat": False,
    "antialias": True,
    "alpha": False,
}


def run_prepare(project: str) -> None:
    """步骤 1：工程后处理。"""
    here = os.path.dirname(os.path.abspath(__file__))
    prep = os.path.join(here, "prepare_unity_project.py")
    if not os.path.isfile(prep):
        print("[!] 未找到 prepare_unity_project.py，跳过")
        return
    print("[1/3] 工程后处理 ------------------------------")
    subprocess.run([sys.executable, prep, "--project", project], check=False)


def run_unity(unity_exe: str, project: str, log_path: str) -> int:
    """步骤 2：注入构建脚本 + 命令行构建。"""
    editor_dir = os.path.join(project, "Assets", "Editor")
    os.makedirs(editor_dir, exist_ok=True)
    with open(os.path.join(editor_dir, "BuildWebGL.cs"), "w", encoding="utf-8") as f:
        f.write(EDITOR_CS)

    cmd = [
        unity_exe, "-batchmode", "-quit", "-nographics",
        "-projectPath", project,
        "-executeMethod", "BuildWebGL.PerformBuild",
        "-buildTarget", "WebGL",
        "-logFile", log_path,
    ]
    print("[2/3] Unity 构建 ------------------------------")
    print("     ", " ".join(cmd))
    t0 = time.time()
    proc = subprocess.run(cmd)
    print("[*] Unity 退出码: %s  耗时 %.1f 分钟" % (proc.returncode, (time.time() - t0) / 60))
    return proc.returncode


def collect_build(src_build_dir: str, out_dir: str, company: str, product: str) -> dict:
    """步骤 3：收集产物并生成 build.json。"""
    print("[3/3] 收集产物 ------------------------------")
    os.makedirs(out_dir, exist_ok=True)
    for name in os.listdir(src_build_dir):
        s = os.path.join(src_build_dir, name)
        d = os.path.join(out_dir, name)
        if os.path.isdir(s):
            if os.path.exists(d):
                shutil.rmtree(d)
            shutil.copytree(s, d)
        else:
            shutil.copy2(s, d)

    build_sub = os.path.join(out_dir, "Build")
    if not os.path.isdir(build_sub):
        build_sub = out_dir

    def find(ext):
        for f in sorted(os.listdir(build_sub)):
            if f.lower().endswith(ext.lower()):
                return f
        return None

    loader, data, framework, code = (
        find(".loader.js"), find(".data"), find(".framework.js"), find(".wasm"),
    )
    missing = [n for n, v in
               (("loader.js", loader), (".data", data),
                (".framework.js", framework), (".wasm", code)) if not v]
    if missing:
        raise RuntimeError("构建产物不完整，缺少: %s（见 Unity 日志）" % ", ".join(missing))

    cfg = {
        "loaderUrl": "build/" + loader,
        "dataUrl": "build/" + data,
        "frameworkUrl": "build/" + framework,
        "codeUrl": "build/" + code,
        "streamingAssetsUrl": "build/StreamingAssets",
        "companyName": company,
        "productName": product,
        "webglContextAttributes": CONTEXT_ATTRS,
    }
    with open(os.path.join(out_dir, "build.json"), "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    print(json.dumps(cfg, ensure_ascii=False, indent=2))
    return cfg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--unity", default=DEFAULT_UNITY, help="Unity Editor 路径")
    ap.add_argument("--project", required=True, help="AssetRipper 导出的工程根")
    ap.add_argument("--out", default="game/build", help="WebGL 产物输出目录")
    ap.add_argument("--company", default="DaXuanBa")
    ap.add_argument("--product", default="Get To Work")
    ap.add_argument("--skip-prepare", action="store_true")
    ap.add_argument("--skip-unity", action="store_true", help="只做收集（复用已有 Builds/WebGL）")
    args = ap.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = args.out if os.path.isabs(args.out) else os.path.join(repo_root, args.out)
    log_path = os.path.join(repo_root, "tools", "unity_build.log")
    src_build = os.path.join(args.project, "Builds", "WebGL")

    if not args.skip_prepare:
        run_prepare(args.project)

    if not args.skip_unity:
        if not os.path.isfile(args.unity):
            print("[!] 找不到 Unity: %s" % args.unity)
            sys.exit(1)
        if run_unity(args.unity, args.project, log_path) != 0:
            print("[!] Unity 构建失败，详见日志: %s" % log_path)
            sys.exit(1)

    if not os.path.isdir(src_build):
        print("[!] 未找到构建输出: %s" % src_build)
        sys.exit(1)

    collect_build(src_build, out_dir, args.company, args.product)
    print("[*] 完成 →", out_dir)
    print("[*] 下一步: python tools/split_package.py --build %s --site .." % out_dir)


if __name__ == "__main__":
    main()
